#include "PluginEditor.h"
#include <BinaryData.h>

// ---------------------------------------------------------------------------
// ResourceProvider: serves web/index.html (and any future assets) from the
// BinaryData generated by juce_add_binary_data. This approach avoids data
// URIs and gives the WebBrowserComponent a real URL context so that JUCE 8
// native integration (window.__JUCE__.backend) is fully functional.
// ---------------------------------------------------------------------------
static std::optional<juce::WebBrowserComponent::Resource> provideResource(const juce::String& path)
{
    // The root request ("/") maps to index.html.
    if (path == "/" || path == "/index.html")
    {
        const char* data   = BinaryData::index_html;
        const int   size   = BinaryData::index_htmlSize;

        return juce::WebBrowserComponent::Resource {
            std::vector<std::byte>(reinterpret_cast<const std::byte*>(data),
                                   reinterpret_cast<const std::byte*>(data) + size),
            "text/html"
        };
    }

    // Unknown path — return nullopt so the browser shows its default error.
    return std::nullopt;
}

// ---------------------------------------------------------------------------
// Build the Options object that:
//   1. Sets a ResourceProvider so index.html is served from binary data.
//   2. Enables native integration (injects window.__JUCE__.backend into the page).
//   3. Registers a listener for "pluginMessage" events emitted by JS via
//      window.__JUCE__.backend.emitEvent("pluginMessage", { type, name, value }).
// ---------------------------------------------------------------------------
static juce::WebBrowserComponent::Options buildBrowserOptions()
{
    return juce::WebBrowserComponent::Options {}
        .withResourceProvider(provideResource)
        .withNativeIntegrationEnabled()
        .withEventListener("pluginMessage",
                           [](const juce::var& message)
                           {
                               // message is the payload object sent from JS:
                               // { type: "ping", name: "test", value: 1 }
                               const auto* obj = message.getDynamicObject();
                               if (obj == nullptr)
                                   return;

                               const juce::String type  = obj->getProperty("type").toString();
                               const juce::String name  = obj->getProperty("name").toString();
                               const juce::var    value = obj->getProperty("value");

                               DBG("JS->C++ message: type=" << type
                                   << " name=" << name
                                   << " value=" << value.toString());
                           });
}

// ---------------------------------------------------------------------------
// PluginEditor
// ---------------------------------------------------------------------------
PluginEditor::PluginEditor(PluginProcessor& p)
    : AudioProcessorEditor(&p), processorRef(p),
      browser(buildBrowserOptions())
{
    setSize(600, 400);

    addAndMakeVisible(browser);

    // Navigate to the resource provider root. The ResourceProvider will receive
    // a request for "/" and return the contents of index.html.
    browser.goToURL(juce::WebBrowserComponent::getResourceProviderRoot());
}

PluginEditor::~PluginEditor() {}

void PluginEditor::paint(juce::Graphics& g)
{
    g.fillAll(juce::Colours::black);
}

void PluginEditor::resized()
{
    browser.setBounds(getLocalBounds());
}
